services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_DB: fleet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: